/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/onlywall1.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/onlywall1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[-0.762, 0.15, -0.123]} scale={[1.025, 6.477, 17.44]} />
      <mesh geometry={nodes.Text001.geometry} material={materials['Material.001']} position={[0.792, 2.528, 1.788]} rotation={[1.558, 0.148, -1.585]} />
      <mesh geometry={nodes.Text002.geometry} material={materials['Material.002']} position={[1.072, 1.451, -1.364]} rotation={[1.558, 0.148, -1.585]} />
      <mesh geometry={nodes.Text003.geometry} material={materials['Material.003']} position={[0.965, 0.43, -1.472]} rotation={[1.558, 0.148, -1.585]} />
    </group>
  )
}

useGLTF.preload('/onlywall1.glb')
