/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/template.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/template.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[76.808, 10.973, 0]} scale={[-57.112, -59.492, -119.021]} />
      <mesh geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[-37.956, 11.276, -228.034]} scale={[-57.112, -59.492, -119.021]} />
    </group>
  )
}

useGLTF.preload('/template.glb')
