/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./aaron-transformed.glb --shadows 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Office(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('./models/aaron-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="works_prev" position={[5730.657, 286.533, 2.865]}>
          <mesh name="work_prev_01_0" castShadow receiveShadow geometry={nodes.work_prev_01_0.geometry} material={materials['material-13']} />
          <mesh name="work_prev_05_4" castShadow receiveShadow geometry={nodes.work_prev_05_4.geometry} material={materials['material-13']} position={[3438.394, 0, 0]} />
          <mesh name="work_prev_02_1" castShadow receiveShadow geometry={nodes.work_prev_02_1.geometry} material={materials['material-12']} position={[859.599, 0, 0]} />
          <mesh name="work_prev_03_2" castShadow receiveShadow geometry={nodes.work_prev_03_2.geometry} material={materials['material-11']} position={[1719.197, 0, 0]} />
          <mesh name="work_prev_06_5" castShadow receiveShadow geometry={nodes.work_prev_06_5.geometry} material={materials['material-11']} position={[4297.993, 0, 0]} />
          <mesh name="work_prev_04_3" castShadow receiveShadow geometry={nodes.work_prev_04_3.geometry} material={materials['material-10']} position={[2578.795, 0, 0]} />
        </group>
        <group name="rig" position={[3189.149, 19.049, -169.167]}>
          <primitive object={nodes.root} />
          <primitive object={nodes['MCH-torsoparent']} />
          <primitive object={nodes['MCH-hand_ikparentL']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentL']} />
          <primitive object={nodes['MCH-hand_ikparentR']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentR']} />
          <primitive object={nodes['MCH-foot_ikparentL']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentL']} />
          <primitive object={nodes['MCH-foot_ikparentR']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentR']} />
        </group>
        <mesh name="Text_Var_02001" castShadow receiveShadow geometry={nodes.Text_Var_02001.geometry} material={materials.Tex_03} position={[93.265, 46.919, -4.431]} scale={[218.828, 284.532, 329.405]} />
        <mesh name="Text_Var_02" castShadow receiveShadow geometry={nodes.Text_Var_02.geometry} material={materials.Tex_03} position={[0.628, -0.57, -4.082]} scale={325.173} />
        <mesh name="Tex_03" castShadow receiveShadow geometry={nodes.Tex_03.geometry} material={materials.Tex_03} scale={821.018} />
        <mesh name="Tex_02_019" castShadow receiveShadow geometry={nodes.Tex_02_019.geometry} material={materials.Tex_02} position={[1082.439, 21.396, -479.564]} />
        <mesh name="Tex_02_018" castShadow receiveShadow geometry={nodes.Tex_02_018.geometry} material={materials.Tex_02} position={[4642.812, 57.755, -441.286]} />
        <mesh name="Tex_02_017001" castShadow receiveShadow geometry={nodes.Tex_02_017001.geometry} material={materials.Tex_02} position={[11664.611, 62.413, -470.158]} />
        <mesh name="Tex_02_017" castShadow receiveShadow geometry={nodes.Tex_02_017.geometry} material={materials.Tex_02} position={[11664.611, 62.413, -470.158]} />
        <mesh name="Tex_02_016" castShadow receiveShadow geometry={nodes.Tex_02_016.geometry} material={materials.Tex_02} position={[11636.431, 0.8, -348.8]} />
        <mesh name="Tex_02_015" castShadow receiveShadow geometry={nodes.Tex_02_015.geometry} material={materials.Tex_02} position={[11636.431, 0.8, -348.8]} />
        <mesh name="Tex_02_014" castShadow receiveShadow geometry={nodes.Tex_02_014.geometry} material={materials.Tex_02} position={[16045.978, 0, -85.961]} />
        <mesh name="Tex_02_013" castShadow receiveShadow geometry={nodes.Tex_02_013.geometry} material={materials.Tex_02} position={[1081.763, 0.233, -483.224]} />
        <mesh name="Tex_02_012" castShadow receiveShadow geometry={nodes.Tex_02_012.geometry} material={materials.Tex_02} position={[11605.813, 126, -479.078]} />
        <mesh name="Tex_02_011" castShadow receiveShadow geometry={nodes.Tex_02_011.geometry} material={materials.Wood_floor} position={[3133.68, 0, 0]} />
        <mesh name="FloorMirror" castShadow receiveShadow geometry={nodes.FloorMirror.geometry} material={materials.Wood_floor} position={[3133.68, 0.821, 0]} />
        <mesh name="Tex_02_010" castShadow receiveShadow geometry={nodes.Tex_02_010.geometry} material={materials.Tex_02} position={[16045.978, 0, -85.961]} />
        <mesh name="Tex_02_004" castShadow receiveShadow geometry={nodes.Tex_02_004.geometry} material={materials.Tex_02} position={[3133.68, 0, 0]} />
        <mesh name="Tex_02_003" castShadow receiveShadow geometry={nodes.Tex_02_003.geometry} material={materials.PaletteMaterial001} position={[3133.68, 0, 0]} />
        <mesh name="Tex_02_002002" castShadow receiveShadow geometry={nodes.Tex_02_002002.geometry} material={materials.Tex_02} position={[3332.325, 33.445, -191.833]} rotation={[-Math.PI, 0.018, -Math.PI]} />
        <mesh name="Tex_02_002001" castShadow receiveShadow geometry={nodes.Tex_02_002001.geometry} material={materials.Tex_02} position={[2402.937, 33.262, -189.113]} />
        <mesh name="Tex_02_001" castShadow receiveShadow geometry={nodes.Tex_02_001.geometry} material={materials.Tex_02} position={[16245.512, 64.865, -444.386]} />
        <group name="Table003" position={[4760.835, -2.09, -4306.802]} scale={157.26}>
          <mesh name="Plane095" castShadow receiveShadow geometry={nodes.Plane095.geometry} material={materials['Material.060']} />
          <mesh name="Plane095_1" castShadow receiveShadow geometry={nodes.Plane095_1.geometry} material={materials.PaletteMaterial001} />
        </group>
        <mesh name="services_text_block" castShadow receiveShadow geometry={nodes.services_text_block.geometry} material={nodes.services_text_block.material} position={[14004.598, 252.46, 0.029]} />
        <mesh name="screen_showreel" castShadow receiveShadow geometry={nodes.screen_showreel.geometry} material={materials['material-04']} position={[2865.328, 286.533, -343.839]} />
        <mesh name="portfolio_text_06002" castShadow receiveShadow geometry={nodes.portfolio_text_06002.geometry} material={materials['Material.012']} position={[11743.628, 299.703, -273.591]} rotation={[-0.021, 1.57, 0.021]} scale={[0.422, 0.598, 1.188]} />
        <mesh name="portfolio_text_06001" castShadow receiveShadow geometry={nodes.portfolio_text_06001.geometry} material={materials['Material.013']} position={[10895.171, 290.826, -263.851]} rotation={[-0.021, 1.57, 0.021]} scale={[0.422, 0.598, 1.188]} />
        <mesh name="portfolio_text_06" castShadow receiveShadow geometry={nodes.portfolio_text_06.geometry} material={nodes.portfolio_text_06.material} position={[10447.699, 287.038, 0.029]} />
        <mesh name="portfolio_text_05" castShadow receiveShadow geometry={nodes.portfolio_text_05.geometry} material={nodes.portfolio_text_05.material} position={[9580.784, 287.038, 0.029]} />
        <mesh name="portfolio_text_04" castShadow receiveShadow geometry={nodes.portfolio_text_04.geometry} material={nodes.portfolio_text_04.material} position={[8730.079, 287.038, 0.029]} />
        <mesh name="portfolio_text_03" castShadow receiveShadow geometry={nodes.portfolio_text_03.geometry} material={nodes.portfolio_text_03.material} position={[7858.798, 287.038, 0.029]} />
        <mesh name="portfolio_text_02" castShadow receiveShadow geometry={nodes.portfolio_text_02.geometry} material={nodes.portfolio_text_02.material} position={[7004.646, 287.038, 0.029]} />
        <mesh name="portfolio_text_01" castShadow receiveShadow geometry={nodes.portfolio_text_01.geometry} material={nodes.portfolio_text_01.material} position={[6151.875, 287.038, 0.029]} />
        <mesh name="portfolio_text_01002" castShadow receiveShadow geometry={nodes.portfolio_text_01002.geometry} material={materials['Material.008']} position={[2296.807, 315.353, -260.52]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={[0.379, 0.544, 0.699]} />
        <mesh name="portfolio_text_01001" castShadow receiveShadow geometry={nodes.portfolio_text_01001.geometry} material={materials['Material.007']} position={[3432.225, 316.713, -261.516]} rotation={[0, -1.528, 0]} scale={[0.379, 0.544, 0.699]} />
        <mesh name="Play_button" castShadow receiveShadow geometry={nodes.Play_button.geometry} material={materials['Material.004']} position={[2864.844, 275.825, -115.224]} />
        <mesh name="Planet_Rotation" castShadow receiveShadow geometry={nodes.Planet_Rotation.geometry} material={materials.Tex_02} position={[16045.839, 286.533, -85.96]} />
        <mesh name="Plane143" castShadow receiveShadow geometry={nodes.Plane143.geometry} material={nodes.Plane143.material} position={[4760.835, -2.09, -4306.802]} scale={157.26} />
        <mesh name="Plane142" castShadow receiveShadow geometry={nodes.Plane142.geometry} material={materials['Material.072']} position={[4760.835, -2.09, -4306.802]} scale={157.26} />
        <group name="Plane136" position={[4760.835, -2.09, -4306.802]} scale={157.26}>
          <mesh name="Plane150" castShadow receiveShadow geometry={nodes.Plane150.geometry} material={materials.PaletteMaterial002} />
          <mesh name="Plane150_1" castShadow receiveShadow geometry={nodes.Plane150_1.geometry} material={materials.PaletteMaterial003} />
        </group>
        <group name="Main_Room001" position={[4760.835, -2.09, -4306.802]} scale={157.26}>
          <mesh name="Cube021" castShadow receiveShadow geometry={nodes.Cube021.geometry} material={materials.Wall_brick} />
          <mesh name="Cube021_1" castShadow receiveShadow geometry={nodes.Cube021_1.geometry} material={nodes.Cube021_1.material} />
        </group>
        <group name="High009" position={[4934.813, -2.09, -4306.802]} scale={157.26}>
          <mesh name="PolySphere013" castShadow receiveShadow geometry={nodes.PolySphere013.geometry} material={materials.Leataher} />
          <mesh name="PolySphere013_1" castShadow receiveShadow geometry={nodes.PolySphere013_1.geometry} material={materials.PaletteMaterial001} />
        </group>
        <mesh name="hello_sign_contact" castShadow receiveShadow geometry={nodes.hello_sign_contact.geometry} material={materials['Material.014']} position={[17046.404, 398.64, 14.091]} />
        <mesh name="GirlSit_03" castShadow receiveShadow geometry={nodes.GirlSit_03.geometry} material={materials.PaletteMaterial004} position={[2393.571, -18.046, -135.121]} rotation={[-1.412, 1.314, 1.351]} scale={[1.062, 0.958, 1.272]} />
        <mesh name="Cube153" castShadow receiveShadow geometry={nodes.Cube153.geometry} material={materials['Material.097']} position={[4760.835, -2.09, -4306.802]} scale={157.26} />
        <mesh name="Cube151" castShadow receiveShadow geometry={nodes.Cube151.geometry} material={materials['Material.095']} position={[4760.835, -2.09, -4306.802]} scale={157.26} />
        <group name="Cube150" position={[4760.835, -2.09, -4306.802]} scale={157.26}>
          <mesh name="Cube163" castShadow receiveShadow geometry={nodes.Cube163.geometry} material={materials['Material.070']} />
          <mesh name="Cube163_1" castShadow receiveShadow geometry={nodes.Cube163_1.geometry} material={materials['Material.067']} />
        </group>
        <group name="Cube147" position={[4760.835, -2.09, -4306.802]} scale={157.26}>
          <mesh name="Cube160" castShadow receiveShadow geometry={nodes.Cube160.geometry} material={materials.Leataher} />
          <mesh name="Cube160_1" castShadow receiveShadow geometry={nodes.Cube160_1.geometry} material={materials.PaletteMaterial001} />
        </group>
        <mesh name="crown_sugn_our_service" castShadow receiveShadow geometry={nodes.crown_sugn_our_service.geometry} material={materials['Material.003']} position={[12035.32, 385.325, 0.029]} scale={[1.52, 1.202, 39.55]} />
        <mesh name="about_text_block001" castShadow receiveShadow geometry={nodes.about_text_block001.geometry} material={materials.PaletteMaterial001} position={[1715.285, 279.178, 0.029]} />
        <mesh name="about_text_block" castShadow receiveShadow geometry={nodes.about_text_block.geometry} material={nodes.about_text_block.material} position={[1715.285, 279.178, 0.029]} />
        <mesh name="Tex_01001" castShadow receiveShadow geometry={nodes.Tex_01001.geometry} material={materials.PaletteMaterial005} position={[3133.68, 0, 0]} />
        <mesh name="Tex_01002" castShadow receiveShadow geometry={nodes.Tex_01002.geometry} material={materials['Tex_01.001']} position={[3133.68, 0, 0]} />
        <group name="Tex_01003" position={[3133.68, 0, 0]}>
          <mesh name="Mesh003" castShadow receiveShadow geometry={nodes.Mesh003.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Mesh003_1" castShadow receiveShadow geometry={nodes.Mesh003_1.geometry} material={materials.Wall_brick} />
        </group>
        <group name="Tex_01004" position={[2738.59, 0, -2670.851]}>
          <mesh name="Mesh016" castShadow receiveShadow geometry={nodes.Mesh016.geometry} material={materials['Tex_01.001']} />
          <mesh name="Mesh016_1" castShadow receiveShadow geometry={nodes.Mesh016_1.geometry} material={materials.Tex_02} />
        </group>
        <mesh name="Mesh_FlagPole1_Mat_Flag_0001" castShadow receiveShadow geometry={nodes.Mesh_FlagPole1_Mat_Flag_0001.geometry} material={materials['Mat_Flag.001']} position={[15844.345, 91.408, -459.624]} scale={[1.427, 1.726, 1.094]} />
        <mesh name="Mesh_FlagPole1_Mat_FlagPole_0001" castShadow receiveShadow geometry={nodes.Mesh_FlagPole1_Mat_FlagPole_0001.geometry} material={materials['Mat_FlagPole.001']} position={[15844.345, 91.408, -459.624]} scale={[1.134, 1.726, 1.094]} />
        <mesh name="pac_man_machine_automat_0" castShadow receiveShadow geometry={nodes.pac_man_machine_automat_0.geometry} material={materials.automat} position={[11446.25, -5.252, -417.832]} rotation={[-Math.PI / 2, 0, 0]} scale={[6.183, 8.02, 5.095]} />
        <mesh name="scheibe_scheibe_0" castShadow receiveShadow geometry={nodes.scheibe_scheibe_0.geometry} material={materials.scheibe} position={[11446.25, -5.252, -417.832]} rotation={[-Math.PI / 2, 0, 0]} scale={[9.862, 8.02, 6.154]} />
        <mesh name="Object_2001" castShadow receiveShadow geometry={nodes.Object_2001.geometry} material={materials.palette} position={[11218.649, -5.04, -332.866]} rotation={[-1.522, -0.02, 0]} scale={[29.13, 30.247, 15.614]} />
        <skinnedMesh name="Ch02_Body" geometry={nodes.Ch02_Body.geometry} material={materials['Ch02_body.001']} skeleton={nodes.Ch02_Body.skeleton} position={[3189.149, 19.049, -169.167]} />
        <skinnedMesh name="Ch02_Cloth" geometry={nodes.Ch02_Cloth.geometry} material={materials['Ch02_body.001']} skeleton={nodes.Ch02_Cloth.skeleton} position={[3189.149, 19.049, -169.167]} />
        <skinnedMesh name="Ch02_Eyelashes" geometry={nodes.Ch02_Eyelashes.geometry} material={materials['Ch02_hair.001']} skeleton={nodes.Ch02_Eyelashes.skeleton} position={[3189.149, 19.049, -169.167]} />
        <skinnedMesh name="Ch02_Sneakers" geometry={nodes.Ch02_Sneakers.geometry} material={materials['Ch02_body.001']} skeleton={nodes.Ch02_Sneakers.skeleton} position={[3189.149, 19.049, -169.167]} />
        <skinnedMesh name="Ch02_Socks" geometry={nodes.Ch02_Socks.geometry} material={materials['Ch02_body.001']} skeleton={nodes.Ch02_Socks.skeleton} position={[3189.149, 19.049, -169.167]} />
      </group>
    </group>
  )
}

useGLTF.preload('/aaron-transformed.glb')
