/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 landscape.glb 
*/
import React, { useRef, useEffect } from 'react';
import ContactForm from '../components/ContactForm';
import * as THREE from 'three';

import {
  useScroll,
  useGLTF,
  PerspectiveCamera,
  useAnimations,
  useTexture,
  Text,
  Html,
  useVideoTexture,
  RoundedBox,
  Image,
} from "@react-three/drei";
import { Decal } from "@react-three/drei";
import { BoxGeometry, MeshBasicMaterial } from "three";
import { useFrame, useThree } from "@react-three/fiber";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faGreaterThan, faPaperclip, faPlay } from "@fortawesome/free-solid-svg-icons";

export function Model(props) {
  const group = React.useRef();
  const element = React.useRef();
  const logoMesh = React.useRef();
  const planetMesh = React.useRef();
  const { nodes, materials, animations } = useGLTF("./models/16finalLiveFile2.glb");
  const { actions } = useAnimations(animations, group);
  const playButtonRef = useRef();
  const ref = useRef();
  const scroll = useScroll();
  const { gl } = useThree();

  // useFrame((state, delta) => {
  //   // const a = clock.getElapsedTime();
  //   logoMesh.current.rotation.y += 0.05;
  //   planetMesh.current.rotation.y += 0.02;
  // });

  useEffect(() => {
    if (!playButtonRef.current) return;

    const video = document.createElement('video');
    video.src = '/video.mp4';
    video.loop = true;
    video.muted = true;
    video.play();

    const videoTexture = new THREE.VideoTexture(video);
    playButtonRef.current.material = new THREE.MeshBasicMaterial({ map: videoTexture });
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="works_prev" position={[5730.657, 286.533, 2.865]}>
          <mesh name="work_prev_01_0" geometry={nodes.work_prev_01_0.geometry} material={materials['material-13']} position={[0, 0, 12.16]} />
          <mesh name="work_prev_02_1" geometry={nodes.work_prev_02_1.geometry} material={materials['material-12']} position={[859.599, 0, 12.16]} />
          <mesh name="work_prev_03_2" geometry={nodes.work_prev_03_2.geometry} material={materials['material-11']} position={[1719.197, 0, 12.16]} />
          <mesh name="work_prev_04_3" geometry={nodes.work_prev_04_3.geometry} material={materials['material-10']} position={[2578.795, 0, 12.16]} />
          <mesh name="work_prev_05_4" geometry={nodes.work_prev_05_4.geometry} material={materials['material-09']} position={[3438.394, 0, 12.16]} />
          <mesh name="work_prev_06_5" geometry={nodes.work_prev_06_5.geometry} material={materials['material-08']} position={[4297.993, 0, 12.16]} />
        </group>
        <group name="Sketchfab_model" position={[15847, 0, -458.41]} rotation={[-Math.PI / 2, 0, 0.274]} scale={215.691}>
          <group name="28180fb1ec9a44a1b6262a52a443f630fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode">
              <group name="Mesh_FlagPole1" position={[0, 1.329, 0]}>
                <mesh name="Mesh_FlagPole1_Mat_Flag_0" geometry={nodes.Mesh_FlagPole1_Mat_Flag_0.geometry} material={materials.Mat_Flag} />
                <mesh name="Mesh_FlagPole1_Mat_FlagPole_0" geometry={nodes.Mesh_FlagPole1_Mat_FlagPole_0.geometry} material={materials.Mat_FlagPole} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model001" position={[11465.542, 0, -388.42]} rotation={[-Math.PI / 2, 0, 0]} scale={5.195}>
          <group name="ad72bb6817744cbea1b39b136ec1313cfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode001">
                <group name="ghost1" position={[-0.926, 37.654, -1.616]} rotation={[-0.815, 0, 0]} scale={0.095}>
                  <mesh name="ghost1_pac_&_ghost_0" geometry={nodes['ghost1_pac_&_ghost_0'].geometry} material={materials.pac__ghost} position={[0.002, 0, 0]} />
                </group>
                <group name="ghost2" position={[6.742, 41.929, -6.15]} rotation={[-0.815, 0, 0]} scale={0.095}>
                  <mesh name="ghost2_pac_&_ghost_0" geometry={nodes['ghost2_pac_&_ghost_0'].geometry} material={materials.pac__ghost} position={[0.002, 0, 0]} />
                </group>
                <group name="ghost3" position={[0.913, 37.645, -1.606]} rotation={[-0.815, 0, 0]} scale={0.095}>
                  <mesh name="ghost3_pac_&_ghost_0" geometry={nodes['ghost3_pac_&_ghost_0'].geometry} material={materials.pac__ghost} />
                </group>
                <group name="ghost4" position={[-3.883, 37.685, -1.649]} rotation={[-0.815, 0, 0]} scale={0.095}>
                  <mesh name="ghost4_pac_&_ghost_0" geometry={nodes['ghost4_pac_&_ghost_0'].geometry} material={materials.pac__ghost} position={[-0.002, 0, 0]} />
                </group>
                <group name="pac_man_machine" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="pac_man_machine_automat_0" geometry={nodes.pac_man_machine_automat_0.geometry} material={materials.automat} />
                </group>
                <group name="pacman" position={[7.338, 37.744, -1.735]} rotation={[-0.815, 0, 0]} scale={0.095}>
                  <group name="mouth_bott" rotation={[0, 0, 0.188]}>
                    <group name="Object_13" position={[0.002, -0.317, 0]}>
                      <mesh name="mouth_bott_pac_&_ghost_0" geometry={nodes['mouth_bott_pac_&_ghost_0'].geometry} material={materials.pac__ghost} />
                    </group>
                  </group>
                  <group name="mouth_top" rotation={[0, 0, -0.188]}>
                    <group name="Object_10" position={[0, -0.317, 0]}>
                      <mesh name="mouth_top_pac_&_ghost_0" geometry={nodes['mouth_top_pac_&_ghost_0'].geometry} material={materials.pac__ghost} />
                    </group>
                  </group>
                  <group name="Object_7" position={[0, -0.317, 0]}>
                    <mesh name="pacman_pac_&_ghost_0" geometry={nodes['pacman_pac_&_ghost_0'].geometry} material={materials.pac__ghost} />
                  </group>
                </group>
                <group name="scheibe" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="scheibe_scheibe_0" geometry={nodes.scheibe_scheibe_0.geometry} material={materials.scheibe} />
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model002" position={[5290.794, 58.591, -1886.18]} rotation={[-1.521, 0.007, -3.073]} scale={6.413}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="bottom_frame_136" position={[-4.199, 5.247, 3.481]} rotation={[-2.832, 1.071, 2.868]} scale={[0.473, 0.282, 2.467]}>
                <mesh name="Object_280" geometry={nodes.Object_280.geometry} material={materials['Material.001']} />
                <mesh name="Object_281" geometry={nodes.Object_281.geometry} material={materials.metal} />
              </group>
              <group name="Cactus_1_135" position={[18.782, 14.141, -16.756]} scale={4.139}>
                <mesh name="Object_275" geometry={nodes.Object_275.geometry} material={materials.White_flower_pot} />
                <mesh name="Object_276" geometry={nodes.Object_276.geometry} material={materials.Bronze_Old} />
                <mesh name="Object_277" geometry={nodes.Object_277.geometry} material={materials.plastic_green_mat_thin} />
                <mesh name="Object_278" geometry={nodes.Object_278.geometry} material={materials.EA_dune_brown_G} />
              </group>
              <group name="Cube001_134" position={[14.104, 12.764, -0.236]} scale={[9.834, 0.702, 39.334]}>
                <mesh name="Object_273" geometry={nodes.Object_273.geometry} material={materials['EA_dune_brown_G.002']} />
              </group>
              <group name="Cube004_133" position={[14.104, 2.288, -0.236]} scale={[8.429, 9.834, 37.93]}>
                <mesh name="Object_271" geometry={nodes.Object_271.geometry} material={materials.material_0} />
              </group>
              <group name="Cube005_132" position={[22.786, -6.842, -0.236]} scale={[0.702, 0.281, 42.144]}>
                <mesh name="Object_269" geometry={nodes.Object_269.geometry} material={materials.Lead} />
              </group>
              <group name="Cube012_131" position={[14.104, 12.764, -0.236]} scale={[9.834, 0.702, 39.334]}>
                <mesh name="Object_267" geometry={nodes.Object_267.geometry} material={materials['Material.005']} />
              </group>
              <group name="leather_130" position={[-12.927, 21.536, 0.29]} rotation={[-Math.PI, 1.091, -Math.PI]} scale={[-6.815, -2.584, -0.943]}>
                <mesh name="Object_265" geometry={nodes.Object_265.geometry} material={materials['Material.002']} />
              </group>
              <group name="leggy_129" position={[-7.58, -2.892, -2.392]} rotation={[-Math.PI, 1.091, -Math.PI]} scale={[59.697, 107.699, 59.697]}>
                <mesh name="Object_262" geometry={nodes.Object_262.geometry} material={materials.metal} />
                <mesh name="Object_263" geometry={nodes.Object_263.geometry} material={materials['Material.001']} />
              </group>
              <group name="metal_frame_128" position={[-10.575, 16.13, 5.858]} rotation={[-1.468, -0.338, -0.562]} scale={0.462}>
                <mesh name="Object_260" geometry={nodes.Object_260.geometry} material={materials.metal} />
              </group>
              <group name="office_workplace_74_obj022_127" position={[32.307, -5.147, -34.557]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.027}>
                <mesh name="Object_258" geometry={nodes.Object_258.geometry} material={materials.ME_Bronze_old_tarn_G} position={[0.001, 0.002, 0]} />
              </group>
              <group name="office_workplace_74_obj023_126" position={[32.307, -5.147, -34.557]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.027}>
                <mesh name="Object_256" geometry={nodes.Object_256.geometry} material={materials.material_0} position={[0.001, 0.002, 0]} />
              </group>
              <group name="office_workplace_74_obj024_125" position={[32.307, -5.147, -34.557]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.027}>
                <mesh name="Object_254" geometry={nodes.Object_254.geometry} material={materials.material_0} position={[0.001, 0.002, 0]} />
              </group>
              <group name="office_workplace_74_obj025_124" position={[32.307, -5.147, -34.557]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.027}>
                <mesh name="Object_252" geometry={nodes.Object_252.geometry} material={materials.ME_basic_fleck_paint} position={[0.001, 0.002, 0]} />
              </group>
              <group name="office_workplace_74_obj026_123" position={[32.307, -5.147, -34.557]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.027}>
                <mesh name="Object_250" geometry={nodes.Object_250.geometry} material={materials.material_0} position={[0.001, 0.002, 0]} />
              </group>
              <group name="office_workplace_74_obj027_122" position={[32.307, -5.147, -34.557]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.027}>
                <mesh name="Object_248" geometry={nodes.Object_248.geometry} material={materials.ME_basic_copper_oxidized} position={[0.001, 0.002, 0]} />
              </group>
              <group name="office_workplace_74_obj028_121" position={[32.307, -5.147, -34.557]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.027}>
                <mesh name="Object_246" geometry={nodes.Object_246.geometry} material={materials.material_0} position={[0.001, 0.002, 0]} />
              </group>
              <group name="office_workplace_74_obj264_120" position={[-16.903, -8.24, 16.189]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_244" geometry={nodes.Object_244.geometry} material={materials.Default_OBJ} position={[-0.004, -0.001, 0]} />
              </group>
              <group name="office_workplace_74_obj265_119" position={[-16.903, -8.24, 16.189]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_242" geometry={nodes.Object_242.geometry} material={materials.Default_OBJ} position={[-0.004, -0.001, 0]} />
              </group>
              <group name="office_workplace_74_obj267_118" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_240" geometry={nodes.Object_240.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj268_117" position={[-16.903, -8.24, 16.189]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_238" geometry={nodes.Object_238.geometry} material={materials.Default_OBJ} position={[-0.004, -0.001, 0]} />
              </group>
              <group name="office_workplace_74_obj269_116" position={[-16.903, -8.24, 16.189]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_236" geometry={nodes.Object_236.geometry} material={materials.Default_OBJ} position={[-0.004, -0.001, 0]} />
              </group>
              <group name="office_workplace_74_obj271_115" position={[-16.1, -8.24, -25.059]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_234" geometry={nodes.Object_234.geometry} material={materials.Car_Paint_Improved} position={[-0.002, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj272_114" position={[-16.1, -8.24, -25.059]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_232" geometry={nodes.Object_232.geometry} material={materials['EA_dune_brown_G.001']} position={[-0.002, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj273_113" position={[-16.1, -8.24, -25.059]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_230" geometry={nodes.Object_230.geometry} material={materials['EA_dune_brown_G.001']} position={[-0.002, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj274_112" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_228" geometry={nodes.Object_228.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj275_111" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_226" geometry={nodes.Object_226.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj276_110" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_224" geometry={nodes.Object_224.geometry} material={materials.GL_depth_absorbsion_02_G} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj277_109" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_222" geometry={nodes.Object_222.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj280_108" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_220" geometry={nodes.Object_220.geometry} material={materials.Generic_Glossy_Shader} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj281_107" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_218" geometry={nodes.Object_218.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj282_106" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_216" geometry={nodes.Object_216.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj283_105" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_214" geometry={nodes.Object_214.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj284_104" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_212" geometry={nodes.Object_212.geometry} material={materials.LI_dist_single_neg_cracks_G} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj285_103" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_210" geometry={nodes.Object_210.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj286_102" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_208" geometry={nodes.Object_208.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj287_101" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_206" geometry={nodes.Object_206.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj288_100" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_204" geometry={nodes.Object_204.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj289_99" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_202" geometry={nodes.Object_202.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj295_98" position={[-16.1, -8.24, -25.059]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_200" geometry={nodes.Object_200.geometry} material={materials.Default_OBJ} position={[-0.002, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj296_97" position={[-16.1, -7.864, -25.059]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_198" geometry={nodes.Object_198.geometry} material={materials.material_0} position={[0, -0.001, 0]} />
              </group>
              <group name="office_workplace_74_obj297_96" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_196" geometry={nodes.Object_196.geometry} material={materials.GL_basic_black_hole_center} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj298_95" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_194" geometry={nodes.Object_194.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj299_94" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_192" geometry={nodes.Object_192.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj300_93" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_190" geometry={nodes.Object_190.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj301_92" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_188" geometry={nodes.Object_188.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj302_91" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_186" geometry={nodes.Object_186.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj303_90" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_184" geometry={nodes.Object_184.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj304_89" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_182" geometry={nodes.Object_182.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj305_88" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_180" geometry={nodes.Object_180.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj306_87" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_178" geometry={nodes.Object_178.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj307_86" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_176" geometry={nodes.Object_176.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj308_85" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_174" geometry={nodes.Object_174.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj309_84" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_172" geometry={nodes.Object_172.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj310_83" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_170" geometry={nodes.Object_170.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj311_82" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_168" geometry={nodes.Object_168.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj312_81" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_166" geometry={nodes.Object_166.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj313_80" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_164" geometry={nodes.Object_164.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj314_79" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_162" geometry={nodes.Object_162.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj315_78" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_160" geometry={nodes.Object_160.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj316_77" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_158" geometry={nodes.Object_158.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj317_76" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_156" geometry={nodes.Object_156.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj318_75" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_154" geometry={nodes.Object_154.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj319_74" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_152" geometry={nodes.Object_152.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj320_73" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_150" geometry={nodes.Object_150.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj321_72" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_148" geometry={nodes.Object_148.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj322_71" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_146" geometry={nodes.Object_146.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj323_70" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_144" geometry={nodes.Object_144.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj324_69" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_142" geometry={nodes.Object_142.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj325_68" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_140" geometry={nodes.Object_140.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj326_67" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_138" geometry={nodes.Object_138.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj327_66" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_136" geometry={nodes.Object_136.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj328_65" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_134" geometry={nodes.Object_134.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj329_64" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_132" geometry={nodes.Object_132.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj330_63" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_130" geometry={nodes.Object_130.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj331_62" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_128" geometry={nodes.Object_128.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj332_61" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_126" geometry={nodes.Object_126.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj333_60" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_124" geometry={nodes.Object_124.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj334_59" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_122" geometry={nodes.Object_122.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj335_58" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_120" geometry={nodes.Object_120.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj336_57" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_118" geometry={nodes.Object_118.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj337_56" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_116" geometry={nodes.Object_116.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj338_55" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_114" geometry={nodes.Object_114.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj339_54" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_112" geometry={nodes.Object_112.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj340_53" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_110" geometry={nodes.Object_110.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj341_52" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_108" geometry={nodes.Object_108.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj342_51" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_106" geometry={nodes.Object_106.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj343_50" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj344_49" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_102" geometry={nodes.Object_102.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj345_48" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj346_47" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj347_46" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_96" geometry={nodes.Object_96.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj348_45" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj349_44" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj350_43" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj351_42" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj352_41" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj353_40" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj354_39" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj355_38" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj356_37" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj357_36" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj358_35" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj359_34" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj360_33" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj361_32" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj362_31" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials.Basic_Matte_Metal} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj363_30" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj364_29" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj365_28" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj366_27" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj367_26" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj368_25" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj369_24" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj370_23" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj371_22" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj372_21" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj373_20" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj374_19" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.GL_basic_black_hole_center} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj375_18" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj376_17" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj381_16" position={[-16.1, -8.24, 17.794]} rotation={[Math.PI / 2, 0, -3.133]} scale={0.029}>
                <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.Default_OBJ} position={[-0.001, 0, 0]} />
              </group>
              <group name="office_workplace_74_obj682_15" position={[32.307, -5.147, -34.557]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.027}>
                <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.MI_fur} position={[0.001, 0.002, 0]} />
              </group>
              <group name="office_workplace_74_obj683_14" position={[32.307, -5.147, -34.557]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.027}>
                <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.material_0} position={[0.001, 0.002, 0]} />
              </group>
              <group name="office_workplace_74_obj684_13" position={[32.307, -5.147, -34.557]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.027}>
                <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.material_0} position={[0.001, 0.002, 0]} />
              </group>
              <group name="office_workplace_74_obj685_12" position={[32.307, -5.147, -34.557]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.027}>
                <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.MI_voronoi_greeble} position={[0.001, 0.002, 0]} />
              </group>
              <group name="office_workplace_74_obj686_11" position={[32.307, -5.147, -34.557]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.027}>
                <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.material_0} position={[0.001, 0.002, 0]} />
              </group>
              <group name="office_workplace_74_obj687_10" position={[32.307, -5.147, -34.557]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.027}>
                <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.ME_worn_red_meigo_G} position={[0.001, 0.002, 0]} />
              </group>
              <group name="office_workplace_74_obj688_9" position={[32.307, -5.147, -34.557]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.027}>
                <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.Default_OBJ} position={[0.001, 0.002, 0]} />
              </group>
              <group name="office_workplace_74_obj689_8" position={[32.307, -5.147, -34.557]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.027}>
                <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.Default_OBJ} position={[0.001, 0.002, 0]} />
              </group>
              <group name="office_workplace_74_obj690_7" position={[32.307, -5.147, -34.557]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.027}>
                <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.Default_OBJ} position={[0.001, 0.002, 0]} />
              </group>
              <group name="office_workplace_74_obj691_6" position={[32.307, -5.147, -34.557]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.027}>
                <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.Default_OBJ} position={[0.001, 0.002, 0]} />
              </group>
              <group name="office_workplace_74_obj692_5" position={[32.307, -5.147, -34.557]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.027}>
                <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.material_0} position={[0.001, 0.002, 0]} />
              </group>
              <group name="office_workplace_74_obj693_4" position={[32.307, -5.147, -34.557]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.027}>
                <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials['Material.008']} position={[0.001, 0.002, 0]} />
              </group>
              <group name="office_workplace_74_obj694_3" position={[32.307, -5.147, -34.557]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.027}>
                <mesh name="Object_10001" geometry={nodes.Object_10001.geometry} material={materials.material_0} position={[0.001, 0.002, 0]} />
              </group>
              <group name="office_workplace_74_obj695_2" position={[32.307, -5.147, -34.557]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.027}>
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Default_OBJ} position={[0.001, 0.002, 0]} />
              </group>
              <group name="Plant_1" position={[11.199, 13.481, -35.505]} scale={5.528}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.Orange_flower_pot} />
                <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.Bronze_Old} />
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.Woll_green} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model003" position={[4496.258, 0, -3457.019]} rotation={[-Math.PI / 2, 0, 3.109]} scale={184.681}>
          <group name="aa383b1f866d4253a11a7b68064fd03efbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode002">
              <group name="BigWhiteTables" rotation={[Math.PI, 0, Math.PI]}>
                <mesh name="BigWhiteTables_BigWhiteTable_0" geometry={nodes.BigWhiteTables_BigWhiteTable_0.geometry} material={materials.BigWhiteTable} />
              </group>
              <group name="BrownChairs" rotation={[Math.PI, 0, Math.PI]}>
                <mesh name="BrownChairs_BrownChair_0" geometry={nodes.BrownChairs_BrownChair_0.geometry} material={materials.BrownChair} />
              </group>
              <group name="ComicTable_LP001" rotation={[Math.PI, 0, Math.PI]} />
              <group name="Computers" rotation={[Math.PI, 0, Math.PI]}>
                <mesh name="Computers_Desktop_0" geometry={nodes.Computers_Desktop_0.geometry} material={materials.Desktop} />
              </group>
              <group name="MeetingTable_New_Tabletop_Joined001" rotation={[Math.PI, 0, Math.PI]}>
                <mesh name="MeetingTable_New_Tabletop_Joined001_meetingTable_0" geometry={nodes.MeetingTable_New_Tabletop_Joined001_meetingTable_0.geometry} material={materials.meetingTable} />
              </group>
              <group name="Shelving" rotation={[Math.PI, 0, Math.PI]} />
              <group name="SmallWhiteTables" rotation={[Math.PI, 0, Math.PI]}>
                <mesh name="SmallWhiteTables_SmallWhiteTable_low001_0" geometry={nodes.SmallWhiteTables_SmallWhiteTable_low001_0.geometry} material={materials['SmallWhiteTable_low.001']} />
              </group>
              <group name="Spine_low001" rotation={[Math.PI, 0, Math.PI]}>
                <mesh name="Spine_low001_SwivlChair_0" geometry={nodes.Spine_low001_SwivlChair_0.geometry} material={materials.SwivlChair} />
                <mesh name="Spine_low001_SwivlChair_BLACK_0" geometry={nodes.Spine_low001_SwivlChair_BLACK_0.geometry} material={materials.SwivlChair_BLACK} />
              </group>
              <group name="WoodenDesks" rotation={[Math.PI, 0, Math.PI]}>
                <mesh name="WoodenDesks_woodenDesk_0" geometry={nodes.WoodenDesks_woodenDesk_0.geometry} material={materials.woodenDesk} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model004" position={[3410.68, 149.791, -178.49]} rotation={[-Math.PI / 2, 0, 0]} scale={3.917}>
          <group name="ee1e57920f9e4f649f8dc0c56c265c54fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode003">
              <group name="stylish_hat" rotation={[0.745, 0, 0]} scale={100}>
                <mesh name="stylish_hat_brim_inner_mat_0" geometry={nodes.stylish_hat_brim_inner_mat_0.geometry} material={materials.brim_inner_mat} />
                <mesh name="stylish_hat_brim_outer_mat_0" geometry={nodes.stylish_hat_brim_outer_mat_0.geometry} material={materials.brim_outer_mat} />
                <mesh name="stylish_hat_hat_mat_0" geometry={nodes.stylish_hat_hat_mat_0.geometry} material={materials.hat_mat} />
                <mesh name="stylish_hat_hat_ribbon_mat_0" geometry={nodes.stylish_hat_hat_ribbon_mat_0.geometry} material={materials.hat_ribbon_mat} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model005" position={[2373.5, 107.83, -123.683]} rotation={[-1.559, -0.05, 1.87]} scale={3.917}>
          <group name="HAIRobjcleanermaterialmergergles">
            <mesh name="Object_10002" geometry={nodes.Object_10002.geometry} material={materials['Material.011']} />
            <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials['Material.011']} />
            <mesh name="Object_12001" geometry={nodes.Object_12001.geometry} material={materials['Material.011']} />
            <mesh name="Object_2001" geometry={nodes.Object_2001.geometry} material={materials.eyebrwo} />
            <mesh name="Object_3" geometry={nodes.Object_3.geometry} material={materials.Body} />
            <mesh name="Object_5001" geometry={nodes.Object_5001.geometry} material={materials['Material.012']} />
            <mesh name="Object_6001" geometry={nodes.Object_6001.geometry} material={materials['Material.011']} />
            <mesh name="Object_7001" geometry={nodes.Object_7001.geometry} material={materials['Material.011']} />
            <mesh name="Object_8001" geometry={nodes.Object_8001.geometry} material={materials['Material.011']} />
            <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials['Material.011']} />
          </group>
        </group>
        <group name="Sketchfab_model006" position={[4831.528, 0, -684.987]} rotation={[-Math.PI / 2, 0, 0]} scale={[628.724, 628.724, 252.966]}>
          <group name="root001">
            <group name="GLTF_SceneRootNode001" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Doormat_0" position={[0.06, 0, -0.057]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="Object_4002" geometry={nodes.Object_4002.geometry} material={materials.Material_1} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model007" position={[5891.04, 531.652, -1873.1]} rotation={[-Math.PI / 2, 0, -1.659]} scale={[56.986, 56.986, 44.026]}>
          <group name="871c5b8e40704d609814d1397c4f47b9fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode004">
              <group name="Cube001" position={[27.941, 19.839, 44.379]} rotation={[-Math.PI / 2, 0, 0]} scale={[160.013, 55.942, 55.942]}>
                <mesh name="Cube001_ac_0" geometry={nodes.Cube001_ac_0.geometry} material={materials.material} position={[-10.101, -2.568, 0]} rotation={[0.011, -0.007, -0.016]} scale={[2.049, 1.013, 1]} />
                <mesh name="Cube001_ac_0001" geometry={nodes.Cube001_ac_0001.geometry} material={materials.material} position={[-18.266, -5.369, 0]} rotation={[0, 0, 0.286]} scale={[2.049, 1.013, 1]} />
                <mesh name="Cube001_ac_0002" geometry={nodes.Cube001_ac_0002.geometry} material={materials.material} position={[-10.006, -64.67, -0.987]} rotation={[0, 0, -3.054]} scale={[2.044, 1.038, 1]} />
                <mesh name="Cube001_ac_0003" geometry={nodes.Cube001_ac_0003.geometry} material={materials.material} position={[-19.913, -67.414, -0.92]} rotation={[0, 0, -3.139]} scale={[2.03, 1.01, 1]} />
              </group>
            </group>
          </group>
        </group>
        <mesh
  name="about_text_block"
  geometry={nodes.about_text_block.geometry}
  material={nodes.about_text_block.material}
  position={[1715.285, 279.178, -9]}
>
  <Html
    portal={{ current: gl.domElement.parentNode }}
    scale={100}
    transformGroup
  >
    <div
      className="about-wall about-wall-text"
      style={{
        width: '40rem',
        position: 'fixed',
        top: '0%',
        left: '0%',
        transform: 'translate(-50%, -50%)',
        willChange: 'transform, opacity',
        pointerEvents: 'none', // Allow pointer events to pass through
      }}
    >
      <div
        className="hello-img"
        style={{
          pointerEvents: 'auto', // Enable interaction specifically for this element
        }}
      >
        <img
          src="./img/hello-icon.svg"
          alt=""
          style={{
            width: '100%',
            height: '100%',
            objectFit: 'contain',
          }}
        />
      </div>
      <h2
        style={{
          fontSize: '36px',
          marginTop: '1rem',
          top: '0',
        }}
      >
        About Trailblazer
      </h2>
      <p>
        Trailblazer Innovations is actually a new style of consultancy that develops the bold
        business idea into a businessable solution. We are both software and hardware developers
        with very good and extremely deep technical capabilities, while loving the future very
        much. Helios, our proprietary framework, allows us to embrace agility and efficiency for
        creative product disruption and life-empowering change in the industries.
        <br />
        Our mission is to deliver innovative, fully functional products quickly and
        cost-effectively, helping businesses turn their ideas into reality without the
        constraints of time and budget.
      </p>
      <a
        href="#"
        className="read-more-btn"
        style={{
          pointerEvents: 'auto', // Enable interaction specifically for this link
        }}
      >
        Read More
      </a>
    </div>
  </Html>
</mesh>

        <mesh name="crown_sugn_our_service" geometry={nodes.crown_sugn_our_service.geometry} material={nodes.crown_sugn_our_service.material} position={[12035.32, 385.325, -9]} >
        <Html
        portal={{ current: gl.domElement.parentNode }}
        scale={100}
        >
              <div className='about-wall about-wall-text'
                style={{
                  width: '40rem',
                  position: 'fixed',
                  top: '0%',
                  left: '0%',
                  transform: 'translate(-50%, -50%)',
                  willChange: 'transform, opacity', 
                  pointerEvents: 'auto',
                }}
              >
                
                <div className='hello-img'>
                  <img
                    src="./img/crown-img.svg"
                    alt=""
                    style={{
                      width: '100%',
                      height: '100%',
                      objectFit: 'contain',
                      
                    }}
                  />
                </div>
              </div>
            
            </Html>
            </mesh>
        <mesh name="hello_sign_contact" geometry={nodes.hello_sign_contact.geometry} material={nodes.hello_sign_contact.material} position={[17046.137, 401.206,-9]} >
        <Html
        portal={{ current: gl.domElement.parentNode }}
        scale={100}
        >
              <div className='about-wall about-wall-text'
                style={{
                  width: '40rem',
                  position: 'fixed',
                  top: '0%',
                  left: '0%',
                  transform: 'translate(-50%, -50%)',
                  willChange: 'transform, opacity', 
                }}
              >
                
                <div className='hello-img'>
                  <img
                    src="./img/hello-icon.svg"
                    alt=""
                    style={{
                      width: '100%',
                      height: '100%',
                      objectFit: 'contain',
                    }}
                  />
                </div>
              </div>
            
            </Html>
        </mesh>
        <mesh 
            name="contact_form_mesh" 
            geometry={nodes.hello_sign_contact.geometry} 
            material={nodes.hello_sign_contact.material} 
            position={[17596.137, 301.206, -3.029]}

            >
                <Html
        portal={{ current: gl.domElement.parentNode }}
        scale={100}
        >
                <ContactForm />
                </Html>
            
            </mesh>
        <mesh name="Play_button" geometry={nodes.Play_button.geometry} material={materials['Material.009']} position={[2864.844, 275.825, -115.224]} />
        <mesh name="portfolio_text_01" geometry={nodes.portfolio_text_01.geometry} material={nodes.portfolio_text_01.material} position={[6151.875, 287.038, -9]} >
  <Html
    portal={{ current: gl.domElement.parentNode }}
    scale={100}
  >
    <div
      className='about-wall work-wall-text work-txt-wal'
      style={{
        width: '40rem',
        position: 'fixed',
        top: '0%',
        left: '-50%',
        transform: 'translate(-50%, -50%)',
        pointerEvents: 'none', // Prevent pointer events on the entire container to allow scroll
      }}
    >
      <h2 style={{ fontSize: '30px', marginTop: '1rem', Top: '0', }}>
        Secure Bag
      </h2>
      <p>
        An incredible safe consumer bag conceived to keep belongings safe in public places. With a unique locking mechanism and tamper-proof materials, the Secure Bag offers a peace of mind for travelers and urban residents.
      </p>
      <a
        href="#"
        className="read-more-btn"
        style={{
          pointerEvents: 'auto', // Enable pointer events specifically for the link
        }}
      >
        View Case
      </a>
    </div>
  </Html>
</mesh>

<mesh name="portfolio_text_02" geometry={nodes.portfolio_text_02.geometry} material={nodes.portfolio_text_02.material} position={[7004.646, 287.038, -9]}>
  <Html portal={{ current: gl.domElement.parentNode }} scale={100}>
    <div
      className="about-wall work-wall-text work-txt-wal"
      style={{
        width: '40rem',
        position: 'fixed',
        top: '0%',
        left: '-50%',
        transform: 'translate(-50%, -50%)',
        pointerEvents: 'none', // Allow pointer events to pass through
      }}
    >
      <h2 style={{ fontSize: '30px', marginTop: '1rem', top: '0' }}>
        Pressure Transducer Monitor
      </h2>
      <p>
        This is to address liquid level being monitored in consumer tanks. Innovative device to keep track of the status of its tanks by an individual remotely, thus improving safety and efficiency in both industrial and consumer practices.
      </p>
      <a
        href="#"
        className="read-more-btn"
        style={{
          pointerEvents: 'auto', // Enable pointer events specifically for the link
        }}
      >
        View Case
      </a>
    </div>
  </Html>
</mesh>

<mesh name="portfolio_text_03" geometry={nodes.portfolio_text_03.geometry} material={nodes.portfolio_text_03.material} position={[7858.798, 287.038, -9]}>
  <Html portal={{ current: gl.domElement.parentNode }} scale={100}>
    <div
      className="about-wall work-wall-text work-txt-wal"
      style={{
        width: '40rem',
        position: 'fixed',
        top: '0%',
        left: '-50%',
        transform: 'translate(-50%, -50%)',
        pointerEvents: 'none', // Allow pointer events to pass through
      }}
    >
      <h2 style={{ fontSize: '30px', marginTop: '1rem', top: '0' }}>
        Cellular-Enabled Medication Adherence Device
      </h2>
      <p>
        It is a revolutionizing device meant to help patients track medication adherence while on the move. It gives real-time alerts and reminders for patients to keep in touch with their treatment plan, improving health outcomes.
      </p>
      <a
        href="#"
        className="read-more-btn"
        style={{
          pointerEvents: 'auto', // Enable pointer events specifically for the link
        }}
      >
        View Case
      </a>
    </div>
  </Html>
</mesh>

<mesh name="portfolio_text_04" geometry={nodes.portfolio_text_04.geometry} material={nodes.portfolio_text_04.material} position={[8730.079, 287.038, -9]}>
  <Html portal={{ current: gl.domElement.parentNode }} scale={100}>
    <div
      className="about-wall work-wall-text work-txt-wal"
      style={{
        width: '40rem',
        position: 'fixed',
        top: '0%',
        left: '-50%',
        transform: 'translate(-50%, -50%)',
        pointerEvents: 'none', // Allow pointer events to pass through
      }}
    >
      <h2 style={{ fontSize: '30px', marginTop: '1rem', top: '0' }}>
        Secure Bag
      </h2>
      <p>
        An incredible safe consumer bag conceived to keep belongings safe in public places. With a unique locking mechanism and tamper-proof materials, the Secure Bag offers a peace of mind for travelers and urban residents.
      </p>
      <a
        href="#"
        className="read-more-btn"
        style={{
          pointerEvents: 'auto', // Enable pointer events specifically for the link
        }}
      >
        View Case
      </a>
    </div>
  </Html>
</mesh>

<mesh name="portfolio_text_05" geometry={nodes.portfolio_text_05.geometry} material={nodes.portfolio_text_05.material} position={[9580.784, 287.038, -9]}>
  <Html portal={{ current: gl.domElement.parentNode }} scale={100}>
    <div
      className="about-wall work-wall-text work-txt-wal"
      style={{
        width: '40rem',
        position: 'fixed',
        top: '0%',
        left: '-50%',
        transform: 'translate(-50%, -50%)',
        pointerEvents: 'none', // Allow pointer events to pass through
      }}
    >
      <h2 style={{ fontSize: '30px', marginTop: '1rem', top: '0' }}>
        Pressure Transducer Monitor
      </h2>
      <p>
        This is to address liquid level being monitored in consumer tanks. Innovative device to keep track of the status of its tanks by an individual remotely, thus improving safety and efficiency in both industrial and consumer practices.
      </p>
      <a
        href="#"
        className="read-more-btn"
        style={{
          pointerEvents: 'auto', // Enable pointer events specifically for the link
        }}
      >
        View Case
      </a>
    </div>
  </Html>
</mesh>

<mesh name="portfolio_text_06" geometry={nodes.portfolio_text_06.geometry} material={nodes.portfolio_text_06.material} position={[10447.699, 287.038, -9]}>
  <Html portal={{ current: gl.domElement.parentNode }} scale={100}>
    <div
      className="about-wall work-wall-text work-txt-wal"
      style={{
        width: '40rem',
        position: 'fixed',
        top: '0%',
        left: '-50%',
        transform: 'translate(-50%, -50%)',
        pointerEvents: 'none', // Allow pointer events to pass through
      }}
    >
      <h2 style={{ fontSize: '30px', marginTop: '1rem', top: '0' }}>
        Cellular-Enabled Medication Adherence Device
      </h2>
      <p>
        It is a revolutionizing device meant to help patients track medication adherence while on the move. It gives real-time alerts and reminders for patients to keep in touch with their treatment plan, improving health outcomes.
      </p>
      <a
        href="#"
        className="read-more-btn"
        style={{
          pointerEvents: 'auto', // Enable pointer events specifically for the link
        }}
      >
        View Case
      </a>
    </div>
  </Html>
</mesh>

        <mesh 
          name="screen_showreel"
          ref={playButtonRef}
          geometry={nodes.screen_showreel.geometry} 
          // material={materials['material-04']} 
          position={[2865.328, 286.533, -343.739]} 
          rotation={[0, Math.PI, Math.PI]} // Keep this rotation for proper initial alignment
          scale={[-1, 1, 1]} // This will flip the mesh horizontally
        />
        <mesh name="services_text_block" geometry={nodes.services_text_block.geometry} material={nodes.services_text_block.material} position={[13504.598, 252.46, -9]}>
  <Html portal={{ current: gl.domElement.parentNode }} scale={100} style={{ width: '1000rem' }}>
    <div
      className="about-wall work-wall-text service-text-row"
      style={{
        width: '1000rem',
        position: 'fixed',
        top: '0%',
        left: '-50%',
        transform: 'translate(-40rem, -50%)',
        pointerEvents: 'none', // Allow pointer events to pass through
      }}
    >
      <div className="service-text-col" style={{ width: '' }}>
        <h5>01</h5>
        <h2 style={{ fontSize: '27px', marginTop: '1rem', top: '0' }}>Hardware Design and Development</h2>
        <p>
          We specialize in creating and building hardware solutions tailored to your requirements. Our work ranges from custom electronics to embedded systems. We design top-notch hardware that is innovative, compatible, dependable, and operates efficiently, striving to meet and surpass industry performance benchmarks.
        </p>
        <a
          href="#"
          className="read-more-btn"
          style={{
            pointerEvents: 'auto', // Enable pointer events specifically for the link
          }}
        >
          View Case
        </a>
      </div>
      <div className="service-text-col">
        <h5>02</h5>
        <h2 style={{ fontSize: '27px', marginTop: '1rem', top: '0' }}>Software and Platform Development</h2>
        <p>
          We develop software applications that are very effective and perfectly qualify our hardware innovations to ensure a total package. Custom applications, cloud-based platforms, IoT solutions; all compatible and very effective on any device or environment necessary from and after becoming a complete solution partner for any customer.
        </p>
        <a
          href="#"
          className="read-more-btn"
          style={{
            pointerEvents: 'auto', // Enable pointer events specifically for the link
          }}
        >
          View Case
        </a>
      </div>
      <div className="service-text-col">
        <h5>03</h5>
        <h2 style={{ fontSize: '27px', marginTop: '1rem', top: '0' }}>Mechanical and Electrical Engineering</h2>
        <p>
          Our engineers bring precision and expertise to every project, whether it’s designing intricate mechanical systems or developing electrical circuits. We work closely with you to deliver integrated engineering solutions that solve real-world challenges and drive performance.
        </p>
        <a
          href="#"
          className="read-more-btn"
          style={{
            pointerEvents: 'auto', // Enable pointer events specifically for the link
          }}
        >
          View Case
        </a>
      </div>
      <div className="service-text-col">
        <h5>04</h5>
        <h2 style={{ fontSize: '27px', marginTop: '1rem', top: '0' }}>Industrial & Packaging Design</h2>
        <p>
          Our products encompass functionality, robustness as well as super beautiful appearance. Although beginning with sketches and 3D modeling, our designs actually fit in real-world applications. Thereafter, our design styles also guarantee that your products will be addressed in ways that will be both protective and eye-catching. Therefore, by function and branding, we give possible solutions for better user experience and highlight your great products.
        </p>
        <a
          href="#"
          className="read-more-btn"
          style={{
            pointerEvents: 'auto', // Enable pointer events specifically for the link
          }}
        >
          View Case
        </a>
      </div>
      <div className="service-text-col">
        <h5>05</h5>
        <h2 style={{ fontSize: '27px', marginTop: '1rem', top: '0' }}>Manufacturing Automation and Production</h2>
        <p>
          We help streamline production processes, reducing costs and time while increasing quality and efficiency. From concept to production, we leverage cutting-edge manufacturing automation techniques to deliver high-quality products at scale, on time, and within budget.
        </p>
        <a
          href="#"
          className="read-more-btn"
          style={{
            pointerEvents: 'auto', // Enable pointer events specifically for the link
          }}
        >
          View Case
        </a>
      </div>
      <div className="service-text-col">
        <h5>06</h5>
        <h2 style={{ fontSize: '27px', marginTop: '1rem', top: '0' }}>Mobile App Development</h2>
        <p>
          Bring life, function and better experiences to iPhones or Android devices through our mobile application development expert team. Whether you really need a companion app with hardware devices or a stand-alone app solution, we can develop user-centric mobile applications to keep your customers glued to the screens.
        </p>
        <a
          href="#"
          className="read-more-btn"
          style={{
            pointerEvents: 'auto', // Enable pointer events specifically for the link
          }}
        >
          View Case
        </a>
      </div>
    </div>
  </Html>
</mesh>

        <group name="Tex_01" position={[3133.68, 0, 0]}>
          <mesh name="Mesh075" geometry={nodes.Mesh075.geometry} material={materials.Tex_01} />
          <mesh name="Mesh075_1" geometry={nodes.Mesh075_1.geometry} material={materials.Material} />
          <mesh name="Mesh075_2" geometry={nodes.Mesh075_2.geometry} material={materials['Material.004']} />
          <mesh name="Mesh075_3" geometry={nodes.Mesh075_3.geometry} material={materials['Material.013']} />
          <mesh name="Mesh075_4" geometry={nodes.Mesh075_4.geometry} material={materials['Material.014']} />
        </group>
        <mesh name="FloorMirror" geometry={nodes.FloorMirror.geometry} material={materials.Tex_02} position={[3133.68, 0.821, 0]} />
        <mesh name="Tex_02_011" geometry={nodes.Tex_02_011.geometry} material={materials.Tex_02} position={[3133.68, 0, 0]} />
        <mesh name="Tex_02_001" geometry={nodes.Tex_02_001.geometry} material={materials.Tex_02} position={[16245.512, 64.865, -444.386]} />
        <mesh name="Tex_02_003" geometry={nodes.Tex_02_003.geometry} material={materials.Tex_02} position={[3133.68, 0, 0]} />
        <mesh name="Tex_02_004" geometry={nodes.Tex_02_004.geometry} material={materials.Tex_02} position={[3133.68, 0, 0]} />
        <mesh name="Tex_02_007" geometry={nodes.Tex_02_007.geometry} material={materials.Tex_02} position={[2325.001, -134.29, -4526.008]} scale={[1.463, 1.396, 0.999]} />
        <mesh name="Tex_02_010" geometry={nodes.Tex_02_010.geometry} material={materials.Tex_02} position={[16045.978, 0, -85.961]} />
        <mesh name="Tex_02_013" geometry={nodes.Tex_02_013.geometry} material={materials.Tex_02} position={[1081.763, 0.233, -483.224]} />
        <mesh name="Tex_02_014" geometry={nodes.Tex_02_014.geometry} material={materials.Tex_02} position={[16045.978, 0, -85.961]} />
        <group name="Tex_02_015" position={[11636.431, 0.8, -348.8]}>
          <mesh name="Tex_02_015001" geometry={nodes.Tex_02_015001.geometry} material={materials.Tex_02} />
          <mesh name="Tex_02_015001_1" geometry={nodes.Tex_02_015001_1.geometry} material={materials['Material.017']} />
        </group>
        <mesh name="Tex_02_016" geometry={nodes.Tex_02_016.geometry} material={materials.Tex_02} position={[11636.431, 0.8, -348.8]} />
        <group name="Tex_02_017" position={[11664.611, 62.413, -470.158]}>
          <mesh name="Tex_02_017001_1" geometry={nodes.Tex_02_017001_1.geometry} material={materials.Tex_02} />
          <mesh name="Tex_02_017001_2" geometry={nodes.Tex_02_017001_2.geometry} material={materials['Material.015']} />
        </group>
        <mesh name="Tex_02_018" geometry={nodes.Tex_02_018.geometry} material={materials.Tex_02} position={[4642.812, 57.755, -441.286]} />
        <mesh name="Tex_02_019" geometry={nodes.Tex_02_019.geometry} material={materials.Tex_02} position={[1082.439, 21.396, -479.564]} />
        <mesh name="Planet_Rotation" geometry={nodes.Planet_Rotation.geometry} material={materials.Tex_02} position={[16045.839, 286.533, -85.96]} />
        <group name="Tex_02_002001" position={[2402.94, 33.262, -189.113]}>
          <mesh name="Tex_02_002001_1" geometry={nodes.Tex_02_002001_1.geometry} material={materials.Tex_02} />
          <mesh name="Tex_02_002001_2" geometry={nodes.Tex_02_002001_2.geometry} material={materials['Material.007']} />
          <mesh name="Tex_02_002001_3" geometry={nodes.Tex_02_002001_3.geometry} material={materials['Material.010']} />
        </group>
        <mesh name="Tex_02_017001" geometry={nodes.Tex_02_017001.geometry} material={materials.Tex_02} position={[11664.611, 62.413, -470.158]} />
        <mesh name="Tex_03" geometry={nodes.Tex_03.geometry} material={materials.Tex_03} scale={821.018} />
        <mesh name="Text_Var_01" geometry={nodes.Text_Var_01.geometry} material={materials.Tex_03} scale={821.018} />
        <mesh name="Mesh_0" geometry={nodes.Mesh_0.geometry} material={materials.Material_0} position={[11263.217, 117.592, -381.476]} scale={124.729} />
        <mesh name="Tex_02_013001" geometry={nodes.Tex_02_013001.geometry} material={materials.Tex_02} position={[5826.782, 2.567, -5037.192]} scale={0.779} />
        <mesh name="Tex_02_019001" geometry={nodes.Tex_02_019001.geometry} material={materials.Tex_02} position={[5827.308, 19.062, -5060.745]} scale={0.779} />
        <mesh name="Tex_02_013002" geometry={nodes.Tex_02_013002.geometry} material={materials.Tex_02} position={[3949, 12.668, -5017.786]} scale={0.779} />
        <mesh name="Tex_02_019002" geometry={nodes.Tex_02_019002.geometry} material={materials.Tex_02} position={[3949.527, 29.163, -5041.339]} scale={0.779} />
        <group name="Tex_02_017002" position={[12515.746, 89.423, -459.157]}>
          <mesh name="Tex_02_017003" geometry={nodes.Tex_02_017003.geometry} material={materials.Tex_02} />
          <mesh name="Tex_02_017003_1" geometry={nodes.Tex_02_017003_1.geometry} material={materials['Material.016']} />
        </group>
        <mesh name="Tex_02_007001" geometry={nodes.Tex_02_007001.geometry} material={materials.Tex_02} position={[3145.845, -2.041, -4551.848]} scale={[1.305, 1.244, 0.89]} />
        <mesh name="Tex_02_003002" geometry={nodes.Tex_02_003002.geometry} material={materials.Tex_02} position={[7146.325, -1.198, 13.411]} />
        <mesh name="Tex_02_003001" geometry={nodes.Tex_02_003001.geometry} material={materials.Tex_02} position={[7145.794, -1.917, -97.033]} />
      </group>
    </group>
  );
}

useGLTF.preload("./models/16finalLiveFile2.glb");
